//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contraindication
    {
        public int id { get; set; }
        public string base_name { get; set; }
        public string disease { get; set; }
        public string with_base { get; set; }
        public string severity { get; set; }
        public string message { get; set; }
    }
}
