//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.orders = new HashSet<order>();
            this.prescriptions = new HashSet<prescription>();
            this.profiles = new HashSet<profile>();
        }
    
        public int c_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string contact { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<prescription> prescriptions { get; set; }
        public virtual ICollection<profile> profiles { get; set; }
    }
}
