//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicalstore
    {
        public medicalstore()
        {
            this.medicines = new HashSet<medicine>();
            this.orders = new HashSet<order>();
            this.Riders = new HashSet<Rider>();
        }
    
        public int store_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string location { get; set; }
        public string images { get; set; }
        public string password { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<medicine> medicines { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<Rider> Riders { get; set; }
    }
}
