//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicine
    {
        public medicine()
        {
            this.medicine_batches = new HashSet<medicine_batches>();
            this.order_items = new HashSet<order_items>();
            this.orders = new HashSet<order>();
        }
    
        public int med_id { get; set; }
        public int store_id { get; set; }
        public string name { get; set; }
        public string base_name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> pills_per_pack { get; set; }
        public string category { get; set; }
        public string strength { get; set; }
    
        public virtual medicalstore medicalstore { get; set; }
        public virtual ICollection<medicine_batches> medicine_batches { get; set; }
        public virtual ICollection<order_items> order_items { get; set; }
        public virtual ICollection<order> orders { get; set; }
    }
}
