//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicine_batches
    {
        public int batch_id { get; set; }
        public int med_id { get; set; }
        public string batch_number { get; set; }
        public int total_pills { get; set; }
        public int remaining_pills { get; set; }
        public string expiry_date { get; set; }
        public Nullable<decimal> purchase_price_per_pack { get; set; }
    
        public virtual medicine medicine { get; set; }
    }
}
