//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.order_items = new HashSet<order_items>();
        }
    
        public int order_id { get; set; }
        public int cust_id { get; set; }
        public int store_id { get; set; }
        public Nullable<int> rider_id { get; set; }
        public Nullable<int> presp_id { get; set; }
        public Nullable<int> medicine_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> total_bill { get; set; }
        public string status { get; set; }
        public string location { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual medicalstore medicalstore { get; set; }
        public virtual medicine medicine { get; set; }
        public virtual ICollection<order_items> order_items { get; set; }
        public virtual prescription prescription { get; set; }
        public virtual Rider Rider { get; set; }
    }
}
