//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_items
    {
        public int item_id { get; set; }
        public int order_id { get; set; }
        public int medicine_id { get; set; }
        public int quantity { get; set; }
        public decimal unit_price { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string med_name { get; set; }
    
        public virtual medicine medicine { get; set; }
        public virtual order order { get; set; }
    }
}
