//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescription_medicine
    {
        public int id { get; set; }
        public int prescription_id { get; set; }
        public string medicine_name { get; set; }
        public int per_day { get; set; }
        public int days { get; set; }
        public int total_quantity { get; set; }
    
        public virtual prescription prescriptions { get; set; }
    }
}
