//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescription
    {
        public prescription()
        {
            this.orders = new HashSet<order>();
            this.prescription_medicine = new HashSet<prescription_medicine>();
        }
    
        public int id { get; set; }
        public int cust_id { get; set; }
        public int profileid { get; set; }
        public string location { get; set; }
        public string rx_image { get; set; }
        public string med_name { get; set; }
        public string potency_ml { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual profile profile { get; set; }
        public virtual ICollection<prescription_medicine> prescription_medicine { get; set; }
    }
}
