//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public profile()
        {
            this.phrs = new HashSet<phr>();
            this.prescriptions = new HashSet<prescription>();
        }
    
        public int id { get; set; }
        public int cus_id { get; set; }
        public string Fullname { get; set; }
        public string relation { get; set; }
        public string gender { get; set; }
        public string contact { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<decimal> default_lat { get; set; }
        public Nullable<decimal> default_long { get; set; }
        public string Addres { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<phr> phrs { get; set; }
        public virtual ICollection<prescription> prescriptions { get; set; }
    }
}
