//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rider
    {
        public Rider()
        {
            this.orders = new HashSet<order>();
        }
    
        public int rider_id { get; set; }
        public Nullable<int> med_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public string vehinfo { get; set; }
        public string photo { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public Nullable<int> total_orders { get; set; }
        public Nullable<decimal> rating { get; set; }
        public Nullable<decimal> current_lat { get; set; }
        public Nullable<decimal> current_lng { get; set; }
    
        public virtual medicalstore medicalstore { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual user user { get; set; }
    }
}
