//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fyp1Entities1 : DbContext
    {
        public fyp1Entities1()
            : base("name=fyp1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<contraindication> contraindications { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<medicalstore> medicalstores { get; set; }
        public DbSet<medicine> medicines { get; set; }
        public DbSet<medicine_batches> medicine_batches { get; set; }
        public DbSet<order_items> order_items { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<phr> phrs { get; set; }
        public DbSet<prescription> prescriptions { get; set; }
        public DbSet<profile> profiles { get; set; }
        public DbSet<Rider> Riders { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<prescription_medicine> prescription_medicine { get; set; }
        public DbSet<subscription_medicines> subscription_medicines { get; set; }
        public DbSet<subscriptions> subscriptions { get; set; }
    }
}
