//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriptions
    {
        public subscriptions()
        {
            this.subscription_medicines = new HashSet<subscription_medicines>();
        }
    
        public int id { get; set; }
        public int cust_id { get; set; }
        public int store_id { get; set; }
        public int day_of_month { get; set; }
        public System.DateTime next_order_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual medicalstore medicalstore { get; set; }
        public virtual ICollection<subscription_medicines> subscription_medicines { get; set; }
    }
}
